### ISSUE TITLE
How is it different from Apache Kafka’s MirrorMaker?

### ISSUE THREAD

**Issue by tarinidash** [SupersonicAds/kafka-snow-white#1]
It would be nice if the wiki section can describe , how snow white is different from Apache Kafka’s MirrorMaker.

**Comment by ncreep2** [comment]
I will add something in the README later on. For now, the answer is that comparing the MirrorMaker, Kafka Snow White should be easier to manage:
- The configuration can be reloaded dynamically via files or Consul
- Each mirror is defined independently with no need to restart or affect other mirrors when a given mirror is changed

**Comment by ncreep2** [comment]
I've added a [comparison section](https://github.com/SupersonicAds/kafka-snow-white#compared-to-other-solutions) in the README.

If it makes sense, I'll close the issue.

Thanks

**Comment by tarinidash** [comment]
Thanks a lot
